### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by yann-soubeyrand** [jonasbark/swiftcontrol#133]
Hello,

I don’t know if this is the best place for feedback, but here it is:
- Though I’m using the latest version available on Google Play Store, I get a banner at the bottom of the screen saying “Restart the app to use the new version”.
- I’m using Zwift Click v2 and the app tells me that a new firmware is available (1.2.0). However, in Zwift Companion, no update is available. It seems that 1.1.0 is indeed the latest firmware version: https://forums.zwift.com/t/whats-the-latest-zwift-equipment-firmware-version/608139.
- A banner in the app is saying “Enable auto-rotation on your device to make sure the app works correctly”, though auto-rotation is enabled.
- The built-in keymap for MyWhoosh does not work for me, only the minus button is shifting gears, not the plus button. Creating a new keymap solves this issue.
- It seems impossible to switch to the MyWhoosh link mode once the “normal” mode has been selected, is it?

The points above should not obscure the fact that this app allows us to easily use our Zwift devices (and maybe our Di2 or AXS buttons in the future), which is great, thanks a lot for that!

One last question, how can we contribute a keymap (for example for Kinomap)? Is there a way to adjust button position on screen using a text box (the placement using touch screen is not always precise)?

**Comment by jonasbark** [comment]
Thank you for your feedback, appreciate it!

> Though I’m using the latest version available on Google Play Store, I get a banner at the bottom of the screen saying “Restart the app to use the new version”.

Yes I should make this clearer. These are "over the air" updates, which require you to force close the app to be applied properly

> I’m using Zwift Click v2 and the app tells me that a new firmware is available (1.2.0). However, in Zwift Companion, no update is available

Fixed that already with the latest patch

> A banner in the app is saying “Enable auto-rotation on your device to make sure the app works correctly”, though auto-rotation is enabled.

True, will remove this in the future

> The built-in keymap for MyWhoosh does not work for me, only the minus button is shifting gears, not the plus button. Creating a new keymap solves this issue.

Can you share your keymap? Click the three dots button on the right of the keymap selector

> It seems impossible to switch to the MyWhoosh link mode once the “normal” mode has been selected, is it?

Not impossible, but also not easy to spot: you can go back, then click on the first step and you can change it again. Ideally both (MyWhoosh Link and "On this device") methods could work at the same time, but not sure if it's worth the effort

> One last question, how can we contribute a keymap (for example for Kinomap)?

WIth the mentioned share button you can send it here and I'll integrate it :) 

> Is there a way to adjust button position on screen using a text box (the placement using touch screen is not always precise)

Not yet, but technically you could export the keymap, adjust it, then import again


I haven't cracked the best UX yet, so I'm thankful for any feedback

**Comment by yann-soubeyrand** [comment]
Thanks for your answers!

> Can you share your keymap? Click the three dots button on the right of the keymap selector

The export action seems to do nothing on my phone, so here is a screenshot:

<img width="1080" height="1459" alt="Image" src="https://github.com/user-attachments/assets/47fe2fcd-4698-4720-90b3-79e63b6ed02d" />

**Comment by jonasbark** [comment]
It's supposed to copy the JSON into your Clipboard - do you use Android / iOS?
Thanks for sharing!

**Comment by yann-soubeyrand** [comment]
Ah OK, sorry, I was expecting a "share with" Android dialog! However, I still don't have anything in my clipboard.

**Comment by yann-soubeyrand** [comment]
It seems that I can only export custom keymaps, not built-in ones.

**Comment by jonasbark** [comment]
Closing this, as 3.3.0 will see some improvements here
